server:
  port: 8080
netty:
  host: 127.0.0.1
  port: 7397
spring:
  data:
    elasticsearch:
      cluster-name: es-test
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
